[project]
name = "temporal-ecs-terraform"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "temporalio~=1.17.0",
    "pydantic-settings",
    "boto3",
]
